# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 994d9dfc0a06c2246759129a6732a831b5c42e331ca4365db7097fae9be405bfa45ea0ca13f04783f29451086ef5e278b2f7a665b01661cadd39e8c5ec8fc90a

test:
  secret_key_base: 2a395b5cc61fea11ee32484dfc47c4f248485228bb3305e99bdac8b1d176b4d2f87cb420405ab018977ba537745967c3ad3c93135f3c1f0efc4d4c2de6ba12c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
